import pandas as pd
import numpy as np

def create_temporal_features(df: pd.DataFrame) -> pd.DataFrame:
    """Extracts time-based features from timestamp."""
    df['hour'] = df['timestamp'].dt.hour
    df['day_of_week'] = df['timestamp'].dt.dayofweek
    df['day_of_month'] = df['timestamp'].dt.day
    df['month'] = df['timestamp'].dt.month
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    
    # Peak hours: Morning 7-9, Evening 16-18 on weekdays
    df['is_morning_peak'] = ((df['hour'] >= 7) & (df['hour'] <= 9) & (df['is_weekend'] == 0)).astype(int)
    df['is_evening_peak'] = ((df['hour'] >= 16) & (df['hour'] <= 18) & (df['is_weekend'] == 0)).astype(int)
    
    return df

def create_lag_rolling_features(df: pd.DataFrame, location_col: str = 'location_id', target_col: str = 'volume') -> pd.DataFrame:
    """Creates lag and rolling features avoiding data leakage."""
    # Ensure sorted order
    df = df.sort_values(by=[location_col, 'timestamp']).copy()
    
    # Lag features
    df['lag_1'] = df.groupby(location_col)[target_col].shift(1)
    df['lag_2'] = df.groupby(location_col)[target_col].shift(2)
    df['lag_3'] = df.groupby(location_col)[target_col].shift(3)
    
    # Rolling features (using closed='left' or shifting to avoid leakage)
    df['rolling_mean_3h'] = df.groupby(location_col)[target_col].transform(lambda x: x.shift(1).rolling(window=3, min_periods=1).mean())
    df['rolling_std_3h'] = df.groupby(location_col)[target_col].transform(lambda x: x.shift(1).rolling(window=3, min_periods=1).std())
    
    # Traffic change
    df['traffic_change'] = df['lag_1'] - df['lag_2']
    
    # Fill NAs generated by shifts
    df = df.fillna(method='bfill').fillna(0)
    
    return df

def create_location_features(df: pd.DataFrame) -> pd.DataFrame:
    """Adds location specific contextual features."""
    # Historical average per location
    loc_avg = df.groupby('location_id')['volume'].mean().rename('loc_hist_avg')
    df = df.merge(loc_avg, on='location_id', how='left')
    return df

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """End-to-end feature engineering."""
    df = create_temporal_features(df)
    df = create_lag_rolling_features(df)
    df = create_location_features(df)
    return df
